services:
  bot:
    build:
      context: ../bot
    env_file:
      - ../.env
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:17.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chicane
    volumes:
      - /opt/docker/la-chicane-bot/database:/var/lib/postgresql/data
    ports:
      - '5432:5432'