name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get version from package.json
      id: get_version
      run: echo "VERSION=$(node -p \"require('./bot/package.json').version\")" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t yvelris/la-chicane-discord-bot:${{ env.VERSION }} -t yvelris/la-chicane-discord-bot:latest -f bot/Dockerfile .

    - name: Push Docker image
      run: |
        docker push yvelris/la-chicane-discord-bot:${{ env.VERSION }}
        docker push yvelris/la-chicane-discord-bot:latest
